### ISSUE TITLE
Graph Token Redirect to localhost failed

### ISSUE THREAD

**Issue by BiasF** [Set-OutlookSignatures/Set-OutlookSignatures#107]
I get a ERR_CONNECTION_REFUSED after loggin in to office 365 for getting the graph token.
The application is created in office 365

The browser is redirected to:
http://localhost:63672/?code=0.AS8AdoQ...............................

**Comment by BiasF** [comment]
Hi,

the auth seems to bee successfull, so I think the reason 2 is my problem.
I updated to 4.11 but it doesn't solve the problem.

So I will wait for the next release with the new MSAL.Net version and hope it will fix my problem.

Is it possible to disable graph? We have a Hybrid environment and just need to connect via LDAP vo the onPrem AD.

Tobias

**Comment by GruberMarkus** [comment]
Graph connection can not be disabled. It is only used when your Exchange/AD configuration absolutely requires it, or you explicitely enable it.

Graph is only used in the following cases:
- GraphOnly is true
- Mailbox is in the cloud and at least one of SetCurrentUserOOFMessage or SetCurrentUserOutlookWebSignature is true
- No connection to on-prem AD
- You use New Outlook

**Comment by GruberMarkus** [comment]
Please let me know if your questions are answered and if this issue can be closed.

Have a great weekend!

**Comment by BiasF** [comment]
Hi,

I think you can close the ticket, I will wait for the new release and test if the new release fix that issue.

Tobias
