### ISSUE TITLE
DOCX Template Font Size Problem

### ISSUE THREAD

**Issue by DaveGBHINC** [Set-OutlookSignatures/Set-OutlookSignatures#118]
### Issue happens in the latest release

- [X] I confirm that the issue happens in the latest release of Set-OutlookSignatures

### Previously solved issues and documentation

- [X] I have searched through previous issues and documentation, but have not found an answer to my issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I created a DOCX template using 9 pt and 11 pt fonts.  All of the 11 pt fonts were converted to 12 pt when viewing from Outlook, but the 9 pt stayed the same.

### Verbose log

```Text
I tried to paste it here, but I get an error that the body is too long.  I'd be happy to send it in another manner.
```

**Comment by DaveGBHINC** [comment]
[Verbose Text.txt](https://github.com/user-attachments/files/15830381/Verbose.Text.txt)

**Comment by GruberMarkus** [comment]
Hi @DaveGBHINC,

please re-upload the verbose log, as the file size is 0 bytes on different systems.

Please also share the DOCX template causing the problem.

**Comment by DaveGBHINC** [comment]
My apologies on the verbose log. 

You are absolutely correct, the .HTM file edited in Word does show the correct font size, so it appears that the issue is with Microsoft here.  I should have expected this, as is usually the case with their less than stellar software.

Thank you

**Comment by GruberMarkus** [comment]
My pleasure!
