### ISSUE TITLE
Error when attempting to reference templates/ ini files in SharePoint Online

### ISSUE THREAD

**Issue by rayakajamon** [Set-OutlookSignatures/Set-OutlookSignatures#119]
### Issue happens in the latest release

- [X] I confirm that the issue happens in the latest release of Set-OutlookSignatures

### Previously solved issues and documentation

- [X] I have searched through previous issues and documentation, but have not found an answer to my issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When attempting to store files in SharePoint (Eliminate VPN) the script tries to open Internet Explorer it hangs with this window open....  My default browser is Edge (Tried with and without IE compatibility mode enabled).  I have also tried with Chrome as the default browser, and I get the same result.

It appears to be this snippet of code
![image](https://github.com/Set-OutlookSignatures/Set-OutlookSignatures/assets/22497886/045b249f-4868-48d1-a300-689c79a18671)

![image](https://github.com/Set-OutlookSignatures/Set-OutlookSignatures/assets/22497886/25e7fe97-1515-4bc6-bc84-85df6ddb3d7d)

Any idea what might be the issue?

Thank you

**Comment by GruberMarkus** [comment]
Hi @rayakajamon,

let's start with the good news: The next release, which is already in testing and will be published in the next few weeks, will be able to connect to SharePoint Online (not SharePoint on-prem) via Microsoft Graph, which will eliminate the problem you describe.

Now to your problem: Set-OutlookSignatures treats SharePoint paths as WebDAV paths and tries to mount them by using the "net use" command of Windows. This only works when the following conditions are all met (as documented in the README file):
- The WebClient service is running
- Port 443 is open towards the SharePoint server
- The firewall does not block WebDAV

The WebClient service needs an Internet Explorer cookie, no other browser will work.

On some systems, this does not work. We do not yet know why, and we will probably not investigate further as it rarely happens and as we have a solution for SharePoint Online in the pipeline.

You have not attached a verbose log. is your SharePoint library hosted on-prem or in SharePoint Online?

**Comment by GruberMarkus** [comment]
Set-OutlookSignatures definitely works with SharePoint Online. It is running fine with SPO in all our test environments.

In the README file, all seven parameters referenced by ExplicIT Consulting contain the following text: `SharePoint document libraries are supported (https only)` - mind the **`https only`**.

If your on-prem environment does not support https, it can't work.

**Comment by GruberMarkus** [comment]
Are you interested in test a preview version which no longer requires Internet Explorer to access SharePoint Online?

If yes, let me know and attach the full output of the script run with the -verbose parameter. The verbose log is needed to determine if your environment suits the beta test requirements.

**Comment by rayakajamon** [comment]
Thank you.  Yes, I am very interested in the test preview version.
[transcript1.txt](https://github.com/user-attachments/files/16195036/transcript1.txt)

I have added the log file.  Please know there isn't much to review as the IE window pops up with the "browser not supported" message.  Like the one I initially sent.

If you need anything else, please let me know.  Thank you so much

**Comment by GruberMarkus** [comment]
Looks good for the preview version.

Things to do before:
1. The https paths do not match the format provided in the README file. Change them accordings (test in a browser if they work, and modify them if needed)
   - BenefactorCircleLicenseFile from 'https://healthesystems2016.sharepoint.com/:u:/r/sites/HesOrganizationalAssets/Outlook%20Signature/License/license.dll?csf=1&web=1&e=14bsjJ' to 'https://healthesystems2016.sharepoint.com/sites/HesOrganizationalAssets/Outlook%20Signature/License/license.dll'
   - SignatureTemplatePath from 'https://healthesystems2016.sharepoint.com/:f:/r/sites/HesOrganizationalAssets/Outlook%20Signature/Templates/Signatures?csf=1&web=1&e=fpEulu' to 'https://healthesystems2016.sharepoint.com/sites/HesOrganizationalAssets/Outlook%20Signature/Templates/Signatures'
   - SignatureIniPath from 'https://healthesystems2016.sharepoint.com/:u:/r/sites/HesOrganizationalAssets/Outlook%20Signature/Config/_Signatures.ini?csf=1&web=1&e=sMbUwr' to 'https://healthesystems2016.sharepoint.com/sites/HesOrganizationalAssets/Outlook%20Signature/Config/_Signatures.ini'
   - ReplacementVariableConfigFile from 'https://healthesystems2016.sharepoint.com/:u:/r/sites/HesOrganizationalAssets/Outlook%20Signature/Config/default%20replacement%20variables.ps1?csf=1&web=1&e=dOonGo' to 'https://healthesystems2016.sharepoint.com/sites/HesOrganizationalAssets/Outlook%20Signature/Config/default%20replacement%20variables.ps1'
2. The problem might be related to new SharePoint Online versions currently being rolled out in waves. What's the output of https://1itservices.sharepoint.com/_vti_pvt/service.cnf (replace "1itservices" with your tenant name)?
3. Post a comment with the verbose log of the script adapted according to step 1, and answer the question from step 2

**Comment by rayakajamon** [comment]
Thank you very much.  I have tried multiple url formats including the ones above but will go through the recommended steps again and provide the log. Here is the output from the SPO url.  Verbose log to come  Thanks again!

![image](https://github.com/user-attachments/assets/50e5cae0-e2fb-400d-a70c-ab7f8d85d322)

**Comment by rayakajamon** [comment]
Thank you so much for the help. It appears to have worked this time.  I tried multiple variations of the url, and thought I followed the format in the READ ME exactly, but I must have had something off.  Apologies for taking your time.  Really appreciate the help!

**Comment by GruberMarkus** [comment]
As you have not provided answers to steps 2 and 3: Do you want to close this issue without testing the preview version?

**Comment by rayakajamon** [comment]
Yes, I would still like to try the preview.  I was adding the output of question #2 when your comment came in.  Thank you

**Comment by GruberMarkus** [comment]
1. Do NOT use this preview version together with the Benefactor Circle add-on!
2. Only use this preview version with test accounts.
3. Add the 'Files.Read.All' Graph permission to the test Entra ID app you use. Add it as delegated permission, not as application permission, grant admin consent, and wait a few minutes. If you need help with this, please take advantage of [ExplicIT Consulting](https://explicitconsulting.at)'s fee-based support.
4. Read the changelog below
5. Replace your local copy of Set-OutlookSignatures.ps1 with the attached file.
6. Run Set-OutlookSignatures with the -verbose parameter and post the full script output. As you do not host a custom GraphConfigFile on SharePoint Online, you do not need to pass the new GraphClientID parameter to the script.

# CHANGELOG
### Changed
- Make simulation mode results for defaultNew and defaultReplyFwd signatures cross-platform compatible by not creating shortcuts (Windows) or symbolic links (Linux, macOS), but actually copying the files.
- Include the file name of the actual signature or OOF reply in simulation mode results for defaultNew, defaultReplyFwd, OOFInternal and OOFExternal files ("defaultNew (sample signature name).htm", for example).
- Update handling of SharePoint WebDAV authentication to reflect not yet documented Microsoft API changes.
- Update sample code `Create-EntraApp.ps1` for new `Files.Read.All` permission and add a hint to consider switching to `Files.SelectedOperations.Selected`.
### Added
- Detect if a template or configuration file path is hosted on SharePoint Online, and use Microsoft Graph to access it. This enables SharePoint Online access on Linux and macOS. To use this, you need to update your Entra ID app with the delegated (not application) permission `Files.Read.All` (`Files.SelectedOperations.Selected` also works, but requires additional configuration). Access to SharePoint on-prem is still limited to Windows and WebDAV with an authentication cookie created in Internet Explorer.
- Add new parameter `GraphClientID`. Must be set when `GraphConfigFile` is hosted on SharePoint Online. See `.\docs\README` for details.
- Show local and UTC time for SimulateTime parameter when in simulation mode.
- Remove trailing null character from file names being enumerated in SharePoint folders. .Net or the WebDAV client sometimes add a null character, which is not allowed in file and path names.
### Fixed
- Do not allow parameter `SignatureCollectionInDrafts` in simulation mode unless `SimulateAndDeploy` is enabled.
- Fix a potential problem with paged Microsoft Graph queries which could lead to an infinite loop.

# Preview version
[Set-OutlookSignatures.rename-to-ps1.txt](https://github.com/user-attachments/files/16197753/Set-OutlookSignatures.rename-to-ps1.txt)

**Comment by GruberMarkus** [comment]
@rayakajamon, what are your thoughts and test results about the preview version?

**Comment by rayakajamon** [comment]
Hi Markus, unfortunately, I have been temporarily pulled into a higher priority project.  I will have to circle back on this.  Apologies.

Hope you have a great day!

-Ray Gonzalez
________________________________

**Comment by GruberMarkus** [comment]
Closing this issue as there is no obvious bug involved.

**Comment by rayakajamon** [comment]
Hi Markus, I hope I find you well.  As mentioned,  my priorities got shifted, so apologies for the delay in getting this to you.

I was recently able to jump back on this project and ran the preview version you shared with me.

I have attached the verbose transcript from my test.  It may be too late but figured it couldn't hurt.

Thank you for all of your help.

-Ray Gonzalez

________________________________
