### ISSUE TITLE
Issue with finding groups with spaces in their name?

### ISSUE THREAD

**Issue by AndreDFC12** [Set-OutlookSignatures/Set-OutlookSignatures#123]
### Issue happens in the latest release

- [X] I confirm that the issue happens in the latest release of Set-OutlookSignatures

### Previously solved issues and documentation

- [X] I have searched through previous issues and documentation, but have not found an answer to my issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm trying to use the group tag in my INI file, but whenever I include a group with a space in it's name, the program returns a "Not found" in the output. I've tried using our AD's netbios domain name and have also tried using AzureAD (we're a hybrid environment, but we solely use Exchange online). I have no issues querying any of the groups with no spaces in the names (with the netbios domain name), but have failed to query multiple of our groups with spaces.

I've also tried updating the display name (as that's another tag parameter) of the group to be it's name with no spaces, and that didn't seem to work either.

Any ideas?

**Comment by GruberMarkus** [comment]
The problem has initially been reported and answered here: https://github.com/Set-OutlookSignatures/Set-OutlookSignatures/discussions/121#discussioncomment-10260032

The next release will contain a fix. In the meantime, you can correct it yourself by following the instructions in the link above.

Please let me know if this solves your problem.

**Comment by AndreDFC12** [comment]
Ah man, how did I miss that?! Thank you for pointing me in the right direction. I'll make the change in the script and update you. Do you have a sense of when the next release is expected?

**Comment by AndreDFC12** [comment]
That seems to have fixed it! Thank you!

**Comment by GruberMarkus** [comment]
> Do you have a sense of when the next release is expected?

Hopefully within the next few weeks, but it could also be two months. I can't be more precise at the moment.

**Comment by GruberMarkus** [comment]
> That seems to have fixed it! Thank you!

My pleasure!
