### ISSUE TITLE
Word not installed or not working correctly. Exit.

### ISSUE THREAD

**Issue by stefano-xy** [Set-OutlookSignatures/Set-OutlookSignatures#93]
Hi,

I'm trying to setup company-wide Outlook signatures, but on my machine Set-OutlookSignatures 4.7.0 can't find Word, although it's installed and works normally.

What I get is:

```
Start Word background process @2023-11-10T19:50:52+01:00@
VERBOSE:   WordProcessPriority: 'Normal' ('32')
VERBOSE: The source code was already compiled and loaded.
  Word not installed or not working correctly. Exit.

InvalidOperation: C:\Users\XXX\Downloads\Set-OutlookSignatures_v4.7.0\Set-OutlookSignatures.ps1:2751
Line |
2751 |  … """ | ForEach-Object { $null = $_.SetPriority($WordProcessPriority) }
     |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because [Deserialized.System.Management.ManagementObject#root\cimv2\Win32_Process] does
     | not contain a method named 'SetPriority'.
```
In issue #80 you mention a PS script to detect Word. I run it and I get `WordFilePath: C:\Program Files\Microsoft Office\Root\Office16\WINWORD.EXE`.

I can start Word if I launch that command.

**Comment by GruberMarkus** [comment]
Hi @stefano-xy,

that looks like a problem already oatched for the next release.

Does this problem only occur in PowerShell (pwsh.exe), and not in Windows PowerShell (powershell.exe)?

If so, change
```
Get-WmiObject Win32_process -Filter "ProcessId = ""$script:COMWordDummyPid""" | ForEach-Object { $null = $_.SetPriority($WordProcessPriority) }
```
to
```
$null = Get-CimInstance Win32_process -Filter "ProcessId = ""$script:COMWordDummyPid""" | Invoke-CimMethod -Name SetPriority -Arguments @{Priority = $WordProcessPriority }
```

and
```
Get-WmiObject Win32_process -Filter "ProcessId = ""$script:COMWordPid""" | ForEach-Object { $null = $_.SetPriority($WordProcessPriority) }
```
to
```
$null = Get-CimInstance Win32_process -Filter "ProcessId = ""$script:COMWordPid""" | Invoke-CimMethod -Name SetPriority -Arguments @{Priority = $WordProcessPriority }
```
.


This change will be included in the next release.


Please let me know if this solves your problem.

**Comment by stefano-xy** [comment]
Ok, I confirm the problem affects both PowerShell and Windows PowerShell. However, with the fix you provided, it's solved and it's solved with both interpreters.

Thank you.

**Comment by GruberMarkus** [comment]
You're welcome!
